apiVersion: v1
kind: Namespace
metadata:
  name: memory-exaust
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: memory-exaust
  namespace: memory-exaust
  labels:
    app: memory-exaust
spec:
  replicas: 3
  selector:
    matchLabels:
      app: memory-exaust
  template:
    metadata:
      labels:
        app: memory-exaust
    spec:
      containers:
      - name: memory-exaust
        image: acrackintheice/memory-exaust-py
        resources:
          limits: 
            memory: 100Mi
            cpu: 200m
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: fast-scaling
  namespace: memory-exaust
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: memory-exaust
  minReplicas: 1
  maxReplicas: 10
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 30
    scaleUp:
      stabilizationWindowSeconds: 5
  metrics:
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80